//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.19 at 10:21:15 PM WAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://uddi.soap.xml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package xml.soap.uddi;
