spring.application.name=Station 1

server.port=8081    
#api.application.secretKey=


#==============================
#= DATA SOURCE
#==============================
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/station1bd
spring.datasource.username=root
spring.datasource.password=Senha123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
debug=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
